MASTER_IMPORT_TAG_PREFIX = "excel-import-"

MASTER_PNL = [
    {
        "group_key": "Avenue Q",
        "sheet": "Ave_Q",
        "year": 2026,
        "match_names": ["Ave Q", "Avenue Q", "aveq", "6835 Avenue Q"],
        "address": "6835 Avenue Q, Houston, Texas",
        "financials": {
            "purchase_price": "555000",
            "down_payment": "145522.37",
            "closing_cost": "25693.33",
            "loan_amount": "416250",
            "interest_rate": "0.07375",
            "loan_term_years": "30",
            "monthly_mortgage_payment": "3685.79",
            "land_value": "85000",
            "annual_depreciation_years": "27.5",
        },
        "months": {
            1: {
                "income": "2900.00",
                "operating_expenses": "1293.63",
                "noi": "1606.37",
                "unit_income": [
                    {"door": 1, "amount": "1800", "status": "occupied"},
                    {"door": 2, "amount": "1500", "status": "airbnb"},
                    {"door": 3, "amount": "1319", "status": "occupied"},
                    {"door": 4, "amount": "1100", "status": "airbnb"},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "2556.26"},
                    {"label": "Depreciation", "amount": "1424.24"},
                ],
            },
            2: {
                "income": "3550.03",
                "operating_expenses": "685.87",
                "noi": "2864.16",
                "unit_income": [
                    {"door": 1, "amount": "1750", "status": "occupied"},
                    {"door": 2, "amount": "700.03", "status": "occupied"},
                    {"door": 3, "amount": "1319", "status": "occupied"},
                    {"door": 4, "amount": "1100", "status": "occupied"},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "2556.26"},
                    {"label": "Depreciation", "amount": "1424.24"},
                ],
            },
            3: {
                "income": "4169",
                "operating_expenses": "1675.76",
                "noi": "2493.24",
                "unit_income": [
                    {"door": 1, "amount": "1750", "status": "occupied"},
                    {"door": 2, "amount": "1500", "status": "occupied"},
                    {"door": 3, "amount": "1319", "status": "occupied"},
                    {"door": 4, "amount": "1100", "status": "occupied"},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "2556.26"},
                    {"label": "Depreciation", "amount": "1424.24"},
                ],
            },
            4: {
                "income": "5817",
                "operating_expenses": "1201.92",
                "noi": "4615.08",
                "unit_income": [
                    {"door": 1, "amount": "1760", "status": "occupied"},
                    {"door": 2, "amount": "1722", "status": "vacant"},
                    {"door": 3, "amount": "1319", "status": "occupied"},
                    {"door": 4, "amount": "1016", "status": "occupied"},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "2556.26"},
                    {"label": "Depreciation", "amount": "1424.24"},
                ],
            },
            5: {
                "income": "5796.20",
                "operating_expenses": "1380.60",
                "noi": "4415.60",
                "unit_income": [
                    {"door": 1, "amount": "1800", "status": "occupied"},
                    {"door": 2, "amount": "1627.20", "status": "occupied"},
                    {"door": 3, "amount": "1319", "status": "airbnb"},
                    {"door": 4, "amount": "1050", "status": "occupied"},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "2556.26"},
                    {"label": "Depreciation", "amount": "1424.24"},
                ],
            },
            6: {
                "income": "5836.00",
                "operating_expenses": "30.00",
                "noi": "5806.00",
                "unit_income": [
                    {"door": 1, "amount": "1760", "status": "occupied"},
                    {"door": 2, "amount": "1707", "status": "occupied"},
                    {"door": 3, "amount": "1319", "status": "airbnb"},
                    {"door": 4, "amount": "1050", "status": "occupied"},
                ],
                "expense_lines": [
                    {"label": "Property Management - Unit 4", "amount": "30", "door": 4},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "2556.26"},
                    {"label": "Depreciation", "amount": "1424.24"},
                ],
            },
            7: {
                "income": "4870.51",
                "operating_expenses": "30.00",
                "noi": "4840.51",
                "unit_income": [
                    {"door": 1, "amount": "1800", "status": "occupied"},
                    {"door": 2, "amount": "701.51", "status": "vacant"},
                    {"door": 3, "amount": "1319", "status": "occupied"},
                    {"door": 4, "amount": "1050", "status": "occupied"},
                ],
                "expense_lines": [
                    {"label": "Property Management - Unit 4", "amount": "30", "door": 4},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "2556.26"},
                    {"label": "Depreciation", "amount": "1424.24"},
                ],
            },
            8: {
                "income": "4511.80",
                "operating_expenses": "30.00",
                "noi": "4481.80",
                "unit_income": [
                    {"door": 1, "amount": "1750", "status": "occupied"},
                    {"door": 2, "amount": "392.80", "status": "vacant"},
                    {"door": 3, "amount": "1319", "status": "occupied"},
                    {"door": 4, "amount": "1050", "status": "occupied"},
                ],
                "expense_lines": [
                    {"label": "Property Management - Unit 4", "amount": "30", "door": 4},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "2556.26"},
                    {"label": "Depreciation", "amount": "1424.24"},
                ],
            },
            9: {
                "income": "5394.89",
                "operating_expenses": "30.00",
                "noi": "5364.89",
                "unit_income": [
                    {"door": 1, "amount": "1800", "status": "occupied"},
                    {"door": 2, "amount": "1225.89", "status": "vacant"},
                    {"door": 3, "amount": "1319", "status": "occupied"},
                    {"door": 4, "amount": "1050", "status": "occupied"},
                ],
                "expense_lines": [
                    {"label": "Property Management - Unit 4", "amount": "30", "door": 4},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "2556.26"},
                    {"label": "Depreciation", "amount": "1424.24"},
                ],
            },
            10: {
                "income": "4767.35",
                "operating_expenses": "30.00",
                "noi": "4737.35",
                "unit_income": [
                    {"door": 1, "amount": "1800", "status": "occupied"},
                    {"door": 2, "amount": "567.35", "status": "vacant"},
                    {"door": 3, "amount": "1350", "status": "occupied"},
                    {"door": 4, "amount": "1050", "status": "occupied"},
                ],
                "expense_lines": [
                    {"label": "Property Management - Unit 4", "amount": "30", "door": 4},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "2556.26"},
                    {"label": "Depreciation", "amount": "1424.24"},
                ],
            },
            11: {
                "income": "5338.11",
                "operating_expenses": "30.00",
                "noi": "5308.11",
                "unit_income": [
                    {"door": 1, "amount": "1750", "status": "occupied"},
                    {"door": 2, "amount": "1138.11", "status": "vacant"},
                    {"door": 3, "amount": "1350", "status": "occupied"},
                    {"door": 4, "amount": "1100", "status": "occupied"},
                ],
                "expense_lines": [
                    {"label": "Property Management - Unit 4", "amount": "30", "door": 4},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "2556.26"},
                    {"label": "Depreciation", "amount": "1424.24"},
                ],
            },
            12: {
                "income": "4200.00",
                "operating_expenses": "30.00",
                "noi": "4170.00",
                "unit_income": [
                    {"door": 1, "amount": "1750", "status": "occupied"},
                    {"door": 2, "amount": "1500", "status": "vacant"},
                    {"door": 3, "amount": "1350", "status": "occupied"},
                    {"door": 4, "amount": "1100", "status": "occupied"},
                ],
                "expense_lines": [
                    {"label": "Property Management - Unit 4", "amount": "30", "door": 4},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "2556.26"},
                    {"label": "Depreciation", "amount": "1424.24"},
                ],
            },
        },
    },
    {
        "group_key": "Bella Jess",
        "sheet": "Bella_Jess",
        "year": 2026,
        "match_names": ["Bella Jess", "BellaJess", "21311 Bella Jess", "21311 Bella Jess Drive"],
        "address": "21311 Bella Jess Drive, Houston, Texas",
        "financials": {
            "purchase_price": "255000",
            "down_payment": "52234.95",
            "closing_cost": "16897.62",
            "loan_amount": "204000",
            "interest_rate": "0.0725",
            "loan_term_years": "30",
            "monthly_mortgage_payment": "2076.13",
            "land_value": "49500",
            "annual_depreciation_years": "27.5",
        },
        "months": {
            1: {
                "income": "2300",
                "operating_expenses": "468.53",
                "noi": "1831.47",
                "expense_lines": [
                    {"label": "Electricity", "amount": "303.38", "door": None},
                    {"label": "Utilities (Landlord Paid)", "amount": "165.15", "door": None},
                ],
            },
            2: {
                "income": "2300",
                "operating_expenses": "411.23",
                "noi": "1888.77",
                "expense_lines": [
                    {"label": "Electricity", "amount": "246.08", "door": None},
                    {"label": "Utilities (Landlord Paid)", "amount": "165.15", "door": None},
                ],
            },
            3: {
                "income": "2300",
                "operating_expenses": "380.50",
                "noi": "1919.50",
                "expense_lines": [
                    {"label": "Electricity", "amount": "215.35", "door": None},
                    {"label": "Utilities (Landlord Paid)", "amount": "165.15", "door": None},
                ],
            },
            4: {
                "income": "2300",
                "operating_expenses": "748.06",
                "noi": "1551.94",
                "expense_lines": [
                    {"label": "Repairs & Maintenance", "amount": "350", "door": None},
                    {"label": "Electricity", "amount": "232.91", "door": None},
                    {"label": "Utilities (Landlord Paid)", "amount": "165.15", "door": None},
                ],
            },
            5: {
                "income": "-2300",
                "operating_expenses": "7773.172",
                "noi": "-10073.172",
                "expense_lines": [
                    {"label": "Property Management Fees", "amount": "100", "door": None},
                    {"label": "Repairs & Maintenance", "amount": "200", "door": None},
                    {"label": "Property Taxes", "amount": "453.67", "door": None},
                    {"label": "Insurance", "amount": "183.83", "door": None},
                    {"label": "Inspection", "amount": "600", "door": None},
                    {"label": "Appraisal", "amount": "825", "door": None},
                    {"label": "HOA Fees", "amount": "37.50", "door": None},
                    {"label": "Transportation Cost", "amount": "242.272", "door": None},
                    {"label": "Legal & Professional Fees", "amount": "350", "door": None},
                    {"label": "Supplies & Materials", "amount": "4500", "door": None},
                    {"label": "Electricity", "amount": "241.63", "door": None},
                    {"label": "Utilities (Landlord Paid)", "amount": "241.63", "door": None},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "1232.50"},
                    {"label": "Depreciation", "amount": "622.727"},
                ],
            },
            6: {
                "income": "-2300",
                "operating_expenses": "2401.272",
                "noi": "-4701.272",
                "expense_lines": [
                    {"label": "Property Management Fees", "amount": "100", "door": None},
                    {"label": "Property Taxes", "amount": "453.67", "door": None},
                    {"label": "Insurance", "amount": "183.83", "door": None},
                    {"label": "HOA Fees", "amount": "37.50", "door": None},
                    {"label": "Advertising / Leasing", "amount": "1000", "door": None},
                    {"label": "Transportation Cost", "amount": "90.852", "door": None},
                    {"label": "Supplies & Materials", "amount": "200", "door": None},
                    {"label": "Electricity", "amount": "306.15", "door": None},
                    {"label": "Utilities (Landlord Paid)", "amount": "306.15", "door": None},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "1232.50"},
                    {"label": "Depreciation", "amount": "622.727"},
                ],
            },
            7: {
                "income": "-2300",
                "operating_expenses": "1315.852",
                "noi": "-3615.852",
                "expense_lines": [
                    {"label": "Property Management Fees", "amount": "100", "door": None},
                    {"label": "Property Taxes", "amount": "453.67", "door": None},
                    {"label": "Insurance", "amount": "183.83", "door": None},
                    {"label": "HOA Fees", "amount": "37.50", "door": None},
                    {"label": "Advertising / Leasing", "amount": "250", "door": None},
                    {"label": "Transportation Cost", "amount": "90.852", "door": None},
                    {"label": "Supplies & Materials", "amount": "200", "door": None},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "1232.50"},
                    {"label": "Depreciation", "amount": "622.727"},
                ],
            },
            8: {
                "income": "-2300",
                "operating_expenses": "1467.272",
                "noi": "-3767.272",
                "expense_lines": [
                    {"label": "Property Management Fees", "amount": "100", "door": None},
                    {"label": "Property Taxes", "amount": "453.67", "door": None},
                    {"label": "Insurance", "amount": "183.83", "door": None},
                    {"label": "HOA Fees", "amount": "37.50", "door": None},
                    {"label": "Advertising / Leasing", "amount": "250", "door": None},
                    {"label": "Transportation Cost", "amount": "242.272", "door": None},
                    {"label": "Supplies & Materials", "amount": "200", "door": None},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "1232.50"},
                    {"label": "Depreciation", "amount": "622.727"},
                ],
            },
            9: {
                "income": "-2300",
                "operating_expenses": "1467.272",
                "noi": "-3767.272",
                "expense_lines": [
                    {"label": "Property Management Fees", "amount": "100", "door": None},
                    {"label": "Property Taxes", "amount": "453.67", "door": None},
                    {"label": "Insurance", "amount": "183.83", "door": None},
                    {"label": "HOA Fees", "amount": "37.50", "door": None},
                    {"label": "Advertising / Leasing", "amount": "250", "door": None},
                    {"label": "Transportation Cost", "amount": "242.272", "door": None},
                    {"label": "Supplies & Materials", "amount": "200", "door": None},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "1232.50"},
                    {"label": "Depreciation", "amount": "622.727"},
                ],
            },
            10: {
                "income": "-2300",
                "operating_expenses": "1867.272",
                "noi": "-4167.272",
                "expense_lines": [
                    {"label": "Property Management Fees", "amount": "100", "door": None},
                    {"label": "Repairs & Maintenance", "amount": "500", "door": None},
                    {"label": "Property Taxes", "amount": "453.67", "door": None},
                    {"label": "Insurance", "amount": "183.83", "door": None},
                    {"label": "HOA Fees", "amount": "37.50", "door": None},
                    {"label": "Advertising / Leasing", "amount": "150", "door": None},
                    {"label": "Transportation Cost", "amount": "242.272", "door": None},
                    {"label": "Supplies & Materials", "amount": "200", "door": None},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "1232.50"},
                    {"label": "Depreciation", "amount": "622.727"},
                ],
            },
            11: {
                "income": "-2300",
                "operating_expenses": "1967.272",
                "noi": "-4267.272",
                "expense_lines": [
                    {"label": "Property Management Fees", "amount": "100", "door": None},
                    {"label": "Repairs & Maintenance", "amount": "650", "door": None},
                    {"label": "Property Taxes", "amount": "453.67", "door": None},
                    {"label": "Insurance", "amount": "183.83", "door": None},
                    {"label": "HOA Fees", "amount": "37.50", "door": None},
                    {"label": "Advertising / Leasing", "amount": "150", "door": None},
                    {"label": "Transportation Cost", "amount": "242.272", "door": None},
                    {"label": "Supplies & Materials", "amount": "150", "door": None},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "1232.50"},
                    {"label": "Depreciation", "amount": "622.727"},
                ],
            },
            12: {
                "income": "0",
                "operating_expenses": "1140.142",
                "noi": "-1140.142",
                "expense_lines": [
                    {"label": "Property Management Fees", "amount": "100", "door": None},
                    {"label": "Repairs & Maintenance", "amount": "200", "door": None},
                    {"label": "Property Taxes", "amount": "453.67", "door": None},
                    {"label": "Insurance", "amount": "183.83", "door": None},
                    {"label": "HOA Fees", "amount": "37.50", "door": None},
                    {"label": "Transportation Cost", "amount": "15.142", "door": None},
                    {"label": "Supplies & Materials", "amount": "150", "door": None},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "1232.50"},
                    {"label": "Depreciation", "amount": "622.727"},
                ],
            },
        },
    },
    {
        "group_key": "Sherman St",
        "sheet": "Sherman",
        "year": 2025,
        "match_names": ["Sherman", "6707 Sherman", "6707 Sherman Street"],
        "address": "6707 Sherman Street, Houston, Texas",
        "financials": {
            "purchase_price": "205000",
            "down_payment": "205000",
            "closing_cost": "5257",
            "land_value": "100470",
            "annual_depreciation_years": "27.5",
        },
        "months": {
            1: {
                "income": "0",
                "operating_expenses": "3657.57",
                "noi": "-3657.57",
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 1", "amount": "30", "door": 1},
                    {"label": "Water - Unit 1", "amount": "167.32", "door": 1},
                    {"label": "Property Management Fees - Unit 2", "amount": "40", "door": 2},
                    {"label": "Cleaning Fees - Unit 2", "amount": "60", "door": 2},
                    {"label": "STR (Hotel Occupancy) - Unit 2", "amount": "250", "door": 2},
                    {"label": "Repairs & Maintenance - Unit 3", "amount": "3000", "door": 3},
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                    {"label": "Internet - Unit 5", "amount": "50.25", "door": 5},
                    {"label": "Property Management Fees - Unit 6", "amount": "30", "door": 6},
                ],
            },
            2: {
                "income": "0",
                "operating_expenses": "310.92",
                "noi": "-310.92",
                "expense_lines": [
                    {"label": "Water - Unit 1", "amount": "140.67", "door": 1},
                    {"label": "Cleaning Fees - Unit 2", "amount": "60", "door": 2},
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                    {"label": "Internet - Unit 5", "amount": "50.25", "door": 5},
                    {"label": "Property Management Fees - Unit 6", "amount": "30", "door": 6},
                ],
            },
            3: {
                "income": "0",
                "operating_expenses": "3250.92",
                "noi": "-3250.92",
                "expense_lines": [
                    {"label": "Water - Unit 1", "amount": "140.67", "door": 1},
                    {"label": "Repairs & Maintenance - Unit 3", "amount": "3000", "door": 3},
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                    {"label": "Internet - Unit 5", "amount": "50.25", "door": 5},
                    {"label": "Property Management Fees - Unit 6", "amount": "30", "door": 6},
                ],
            },
            4: {
                "income": "0",
                "operating_expenses": "285.36",
                "noi": "-285.36",
                "expense_lines": [
                    {"label": "Water - Unit 1", "amount": "175.11", "door": 1},
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                    {"label": "Internet - Unit 5", "amount": "50.25", "door": 5},
                    {"label": "Property Management Fees - Unit 6", "amount": "30", "door": 6},
                ],
            },
            5: {
                "income": "0",
                "operating_expenses": "343.05",
                "noi": "-343.05",
                "expense_lines": [
                    {"label": "Water - Unit 1", "amount": "232.80", "door": 1},
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                    {"label": "Internet - Unit 5", "amount": "50.25", "door": 5},
                    {"label": "Property Management Fees - Unit 6", "amount": "30", "door": 6},
                ],
            },
            6: {
                "income": "0",
                "operating_expenses": "2296.14",
                "noi": "-2296.14",
                "expense_lines": [
                    {"label": "Water - Unit 1", "amount": "155.06", "door": 1},
                    {"label": "Repairs & Maintenance - Unit 3", "amount": "2000", "door": 3},
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                    {"label": "Internet - Unit 5", "amount": "81.08", "door": 5},
                    {"label": "Property Management Fees - Unit 6", "amount": "30", "door": 6},
                ],
            },
            7: {
                "income": "0",
                "operating_expenses": "141.08",
                "noi": "-141.08",
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                    {"label": "Internet - Unit 5", "amount": "81.08", "door": 5},
                    {"label": "Property Management Fees - Unit 6", "amount": "30", "door": 6},
                ],
                "financing_lines": [
                    {"label": "Depreciation", "amount": "316.76"},
                ],
            },
            8: {
                "income": "0",
                "operating_expenses": "60.00",
                "noi": "-60.00",
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                    {"label": "Property Management Fees - Unit 6", "amount": "30", "door": 6},
                ],
                "financing_lines": [
                    {"label": "Depreciation", "amount": "316.76"},
                ],
            },
            9: {
                "income": "0",
                "operating_expenses": "60.00",
                "noi": "-60.00",
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                    {"label": "Property Management Fees - Unit 6", "amount": "30", "door": 6},
                ],
                "financing_lines": [
                    {"label": "Depreciation", "amount": "316.76"},
                ],
            },
            10: {
                "income": "0",
                "operating_expenses": "60.00",
                "noi": "-60.00",
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                    {"label": "Property Management Fees - Unit 6", "amount": "30", "door": 6},
                ],
                "financing_lines": [
                    {"label": "Depreciation", "amount": "316.76"},
                ],
            },
            11: {
                "income": "0",
                "operating_expenses": "60.00",
                "noi": "-60.00",
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                    {"label": "Property Management Fees - Unit 6", "amount": "30", "door": 6},
                ],
                "financing_lines": [
                    {"label": "Depreciation", "amount": "316.76"},
                ],
            },
            12: {
                "income": "0",
                "operating_expenses": "60.00",
                "noi": "-60.00",
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                    {"label": "Property Management Fees - Unit 6", "amount": "30", "door": 6},
                ],
                "financing_lines": [
                    {"label": "Depreciation", "amount": "316.76"},
                ],
            },
        },
    },
    {
        "group_key": "Tomball",
        "sheet": "Tomball",
        "year": 2026,
        "match_names": ["Tomball", "21311 Bella Jess Drive Tomball"],
        "address": "21311 Bella Jess Drive, Houston, Texas",
        "financials": {
            "land_value": "49500",
            "annual_depreciation_years": "27.5",
        },
        "months": {
            1: {
                "income": "0",
                "operating_expenses": "458",
                "noi": "-458",
                "expense_lines": [
                    {"label": "Electricity", "amount": "149", "door": None},
                    {"label": "Water", "amount": "80", "door": None},
                    {"label": "Utilities (Landlord Paid)", "amount": "229", "door": None},
                ],
            },
            2: {
                "income": "0",
                "operating_expenses": "458",
                "noi": "-458",
                "expense_lines": [
                    {"label": "Electricity", "amount": "149", "door": None},
                    {"label": "Water", "amount": "80", "door": None},
                    {"label": "Utilities (Landlord Paid)", "amount": "229", "door": None},
                ],
            },
            3: {
                "income": "0",
                "operating_expenses": "458",
                "noi": "-458",
                "expense_lines": [
                    {"label": "Electricity", "amount": "149", "door": None},
                    {"label": "Water", "amount": "80", "door": None},
                    {"label": "Utilities (Landlord Paid)", "amount": "229", "door": None},
                ],
            },
            4: {
                "income": "0",
                "operating_expenses": "458",
                "noi": "-458",
                "expense_lines": [
                    {"label": "Electricity", "amount": "149", "door": None},
                    {"label": "Water", "amount": "80", "door": None},
                    {"label": "Utilities (Landlord Paid)", "amount": "229", "door": None},
                ],
            },
            5: {
                "income": "0",
                "operating_expenses": "7760.542",
                "noi": "-7760.542",
                "expense_lines": [
                    {"label": "Property Management Fees", "amount": "100", "door": None},
                    {"label": "Repairs & Maintenance", "amount": "200", "door": None},
                    {"label": "Property Taxes", "amount": "453.67", "door": None},
                    {"label": "Insurance", "amount": "183.83", "door": None},
                    {"label": "Inspection", "amount": "600", "door": None},
                    {"label": "Appraisal", "amount": "825", "door": None},
                    {"label": "HOA Fees", "amount": "37.50", "door": None},
                    {"label": "Transportation Cost", "amount": "242.272", "door": None},
                    {"label": "Legal & Professional Fees", "amount": "350", "door": None},
                    {"label": "Supplies & Materials", "amount": "4500", "door": None},
                    {"label": "Electricity", "amount": "149", "door": None},
                    {"label": "Water", "amount": "80", "door": None},
                    {"label": "Utilities (Landlord Paid)", "amount": "229", "door": None},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "1232.50"},
                ],
            },
            6: {
                "income": "0",
                "operating_expenses": "2126.352",
                "noi": "-2126.352",
                "expense_lines": [
                    {"label": "Property Management Fees", "amount": "100", "door": None},
                    {"label": "Property Taxes", "amount": "453.67", "door": None},
                    {"label": "Insurance", "amount": "183.83", "door": None},
                    {"label": "HOA Fees", "amount": "37.50", "door": None},
                    {"label": "Advertising / Leasing", "amount": "1000", "door": None},
                    {"label": "Transportation Cost", "amount": "90.852", "door": None},
                    {"label": "Supplies & Materials", "amount": "200", "door": None},
                    {"label": "Electricity", "amount": "11.23", "door": None},
                    {"label": "Water", "amount": "20", "door": None},
                    {"label": "Utilities (Landlord Paid)", "amount": "31.23", "door": None},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "1232.50"},
                ],
            },
            7: {
                "income": "0",
                "operating_expenses": "1449.022",
                "noi": "-1449.022",
                "expense_lines": [
                    {"label": "Property Management Fees", "amount": "100", "door": None},
                    {"label": "Property Taxes", "amount": "453.67", "door": None},
                    {"label": "Insurance", "amount": "183.83", "door": None},
                    {"label": "HOA Fees", "amount": "37.50", "door": None},
                    {"label": "Advertising / Leasing", "amount": "250", "door": None},
                    {"label": "Transportation Cost", "amount": "90.852", "door": None},
                    {"label": "Supplies & Materials", "amount": "200", "door": None},
                    {"label": "Electricity", "amount": "83.17", "door": None},
                    {"label": "Water", "amount": "50", "door": None},
                    {"label": "Utilities (Landlord Paid)", "amount": "133.17", "door": None},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "1232.50"},
                ],
            },
            8: {
                "income": "0",
                "operating_expenses": "1705.472",
                "noi": "-1705.472",
                "expense_lines": [
                    {"label": "Property Management Fees", "amount": "100", "door": None},
                    {"label": "Property Taxes", "amount": "453.67", "door": None},
                    {"label": "Insurance", "amount": "183.83", "door": None},
                    {"label": "HOA Fees", "amount": "37.50", "door": None},
                    {"label": "Advertising / Leasing", "amount": "250", "door": None},
                    {"label": "Transportation Cost", "amount": "242.272", "door": None},
                    {"label": "Supplies & Materials", "amount": "200", "door": None},
                    {"label": "Electricity", "amount": "108.20", "door": None},
                    {"label": "Water", "amount": "130", "door": None},
                    {"label": "Utilities (Landlord Paid)", "amount": "238.20", "door": None},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "1232.50"},
                ],
            },
            9: {
                "income": "0",
                "operating_expenses": "1627.502",
                "noi": "-1627.502",
                "expense_lines": [
                    {"label": "Property Management Fees", "amount": "100", "door": None},
                    {"label": "Property Taxes", "amount": "453.67", "door": None},
                    {"label": "Insurance", "amount": "183.83", "door": None},
                    {"label": "HOA Fees", "amount": "37.50", "door": None},
                    {"label": "Advertising / Leasing", "amount": "250", "door": None},
                    {"label": "Transportation Cost", "amount": "242.272", "door": None},
                    {"label": "Supplies & Materials", "amount": "200", "door": None},
                    {"label": "Electricity", "amount": "118.66", "door": None},
                    {"label": "Water", "amount": "41.57", "door": None},
                    {"label": "Utilities (Landlord Paid)", "amount": "160.23", "door": None},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "1232.50"},
                ],
            },
            10: {
                "income": "0",
                "operating_expenses": "1980.852",
                "noi": "-1980.852",
                "expense_lines": [
                    {"label": "Property Management Fees", "amount": "100", "door": None},
                    {"label": "Repairs & Maintenance", "amount": "500", "door": None},
                    {"label": "Property Taxes", "amount": "453.67", "door": None},
                    {"label": "Insurance", "amount": "183.83", "door": None},
                    {"label": "HOA Fees", "amount": "37.50", "door": None},
                    {"label": "Advertising / Leasing", "amount": "150", "door": None},
                    {"label": "Transportation Cost", "amount": "242.272", "door": None},
                    {"label": "Supplies & Materials", "amount": "200", "door": None},
                    {"label": "Electricity", "amount": "19.22", "door": None},
                    {"label": "Water", "amount": "94.36", "door": None},
                    {"label": "Utilities (Landlord Paid)", "amount": "113.58", "door": None},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "1232.50"},
                ],
            },
            11: {
                "income": "0",
                "operating_expenses": "2128.852",
                "noi": "-2128.852",
                "expense_lines": [
                    {"label": "Property Management Fees", "amount": "100", "door": None},
                    {"label": "Repairs & Maintenance", "amount": "650", "door": None},
                    {"label": "Property Taxes", "amount": "453.67", "door": None},
                    {"label": "Insurance", "amount": "183.83", "door": None},
                    {"label": "HOA Fees", "amount": "37.50", "door": None},
                    {"label": "Advertising / Leasing", "amount": "150", "door": None},
                    {"label": "Transportation Cost", "amount": "242.272", "door": None},
                    {"label": "Supplies & Materials", "amount": "150", "door": None},
                    {"label": "Electricity", "amount": "17.22", "door": None},
                    {"label": "Water", "amount": "144.36", "door": None},
                    {"label": "Utilities (Landlord Paid)", "amount": "161.58", "door": None},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "1232.50"},
                ],
            },
            12: {
                "income": "0",
                "operating_expenses": "1262.312",
                "noi": "-1262.312",
                "expense_lines": [
                    {"label": "Property Management Fees", "amount": "100", "door": None},
                    {"label": "Repairs & Maintenance", "amount": "200", "door": None},
                    {"label": "Property Taxes", "amount": "453.67", "door": None},
                    {"label": "Insurance", "amount": "183.83", "door": None},
                    {"label": "HOA Fees", "amount": "37.50", "door": None},
                    {"label": "Transportation Cost", "amount": "15.142", "door": None},
                    {"label": "Supplies & Materials", "amount": "150", "door": None},
                    {"label": "Electricity", "amount": "17.53", "door": None},
                    {"label": "Water", "amount": "104.64", "door": None},
                    {"label": "Utilities (Landlord Paid)", "amount": "122.17", "door": None},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "1232.50"},
                ],
            },
        },
    },
    {
        "group_key": "Conroe",
        "sheet": "Conroe",
        "year": 2026,
        "match_names": ["Conroe"],
        "address": "21311 Bella Jess Drive, Houston, Texas",
        "financials": {
            "land_value": "49500",
            "annual_depreciation_years": "27.5",
        },
        "months": {
            1: {"income": "0", "operating_expenses": "0", "noi": "0"},
            2: {"income": "0", "operating_expenses": "0", "noi": "0"},
            3: {"income": "0", "operating_expenses": "0", "noi": "0"},
            4: {"income": "0", "operating_expenses": "0", "noi": "0"},
            5: {
                "income": "0",
                "operating_expenses": "7760.54",
                "noi": "-7760.54",
                "expense_lines": [
                    {"label": "Property Management Fees", "amount": "100", "door": None},
                    {"label": "Repairs & Maintenance", "amount": "200", "door": None},
                    {"label": "Property Taxes", "amount": "453.67", "door": None},
                    {"label": "Insurance", "amount": "183.83", "door": None},
                    {"label": "Inspection", "amount": "600", "door": None},
                    {"label": "Appraisal", "amount": "825", "door": None},
                    {"label": "HOA Fees", "amount": "37.50", "door": None},
                    {"label": "Transportation Cost", "amount": "242.27", "door": None},
                    {"label": "Legal & Professional Fees", "amount": "350", "door": None},
                    {"label": "Supplies & Materials", "amount": "4500", "door": None},
                    {"label": "Electricity", "amount": "149", "door": None},
                    {"label": "Water", "amount": "80", "door": None},
                    {"label": "Utilities (Landlord Paid)", "amount": "229", "door": None},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "1232.50"},
                ],
            },
            6: {
                "income": "0",
                "operating_expenses": "2126.35",
                "noi": "-2126.35",
                "expense_lines": [
                    {"label": "Property Management Fees", "amount": "100", "door": None},
                    {"label": "Property Taxes", "amount": "453.67", "door": None},
                    {"label": "Insurance", "amount": "183.83", "door": None},
                    {"label": "HOA Fees", "amount": "37.50", "door": None},
                    {"label": "Advertising / Leasing", "amount": "1000", "door": None},
                    {"label": "Transportation Cost", "amount": "90.85", "door": None},
                    {"label": "Supplies & Materials", "amount": "200", "door": None},
                    {"label": "Electricity", "amount": "11.23", "door": None},
                    {"label": "Water", "amount": "20", "door": None},
                    {"label": "Utilities (Landlord Paid)", "amount": "31.23", "door": None},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "1232.50"},
                ],
            },
            7: {
                "income": "0",
                "operating_expenses": "1449.02",
                "noi": "-1449.02",
                "expense_lines": [
                    {"label": "Property Management Fees", "amount": "100", "door": None},
                    {"label": "Property Taxes", "amount": "453.67", "door": None},
                    {"label": "Insurance", "amount": "183.83", "door": None},
                    {"label": "HOA Fees", "amount": "37.50", "door": None},
                    {"label": "Advertising / Leasing", "amount": "250", "door": None},
                    {"label": "Transportation Cost", "amount": "90.85", "door": None},
                    {"label": "Supplies & Materials", "amount": "200", "door": None},
                    {"label": "Electricity", "amount": "83.17", "door": None},
                    {"label": "Water", "amount": "50", "door": None},
                    {"label": "Utilities (Landlord Paid)", "amount": "133.17", "door": None},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "1232.50"},
                ],
            },
            8: {
                "income": "0",
                "operating_expenses": "1705.47",
                "noi": "-1705.47",
                "expense_lines": [
                    {"label": "Property Management Fees", "amount": "100", "door": None},
                    {"label": "Property Taxes", "amount": "453.67", "door": None},
                    {"label": "Insurance", "amount": "183.83", "door": None},
                    {"label": "HOA Fees", "amount": "37.50", "door": None},
                    {"label": "Advertising / Leasing", "amount": "250", "door": None},
                    {"label": "Transportation Cost", "amount": "242.27", "door": None},
                    {"label": "Supplies & Materials", "amount": "200", "door": None},
                    {"label": "Electricity", "amount": "108.20", "door": None},
                    {"label": "Water", "amount": "130", "door": None},
                    {"label": "Utilities (Landlord Paid)", "amount": "238.20", "door": None},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "1232.50"},
                ],
            },
            9: {
                "income": "0",
                "operating_expenses": "1627.50",
                "noi": "-1627.50",
                "expense_lines": [
                    {"label": "Property Management Fees", "amount": "100", "door": None},
                    {"label": "Property Taxes", "amount": "453.67", "door": None},
                    {"label": "Insurance", "amount": "183.83", "door": None},
                    {"label": "HOA Fees", "amount": "37.50", "door": None},
                    {"label": "Advertising / Leasing", "amount": "250", "door": None},
                    {"label": "Transportation Cost", "amount": "242.27", "door": None},
                    {"label": "Supplies & Materials", "amount": "200", "door": None},
                    {"label": "Electricity", "amount": "118.66", "door": None},
                    {"label": "Water", "amount": "41.57", "door": None},
                    {"label": "Utilities (Landlord Paid)", "amount": "160.23", "door": None},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "1232.50"},
                ],
            },
            10: {
                "income": "0",
                "operating_expenses": "1980.85",
                "noi": "-1980.85",
                "expense_lines": [
                    {"label": "Property Management Fees", "amount": "100", "door": None},
                    {"label": "Repairs & Maintenance", "amount": "500", "door": None},
                    {"label": "Property Taxes", "amount": "453.67", "door": None},
                    {"label": "Insurance", "amount": "183.83", "door": None},
                    {"label": "HOA Fees", "amount": "37.50", "door": None},
                    {"label": "Advertising / Leasing", "amount": "150", "door": None},
                    {"label": "Transportation Cost", "amount": "242.27", "door": None},
                    {"label": "Supplies & Materials", "amount": "200", "door": None},
                    {"label": "Electricity", "amount": "19.22", "door": None},
                    {"label": "Water", "amount": "94.36", "door": None},
                    {"label": "Utilities (Landlord Paid)", "amount": "113.58", "door": None},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "1232.50"},
                ],
            },
            11: {
                "income": "0",
                "operating_expenses": "2128.85",
                "noi": "-2128.85",
                "expense_lines": [
                    {"label": "Property Management Fees", "amount": "100", "door": None},
                    {"label": "Repairs & Maintenance", "amount": "650", "door": None},
                    {"label": "Property Taxes", "amount": "453.67", "door": None},
                    {"label": "Insurance", "amount": "183.83", "door": None},
                    {"label": "HOA Fees", "amount": "37.50", "door": None},
                    {"label": "Advertising / Leasing", "amount": "150", "door": None},
                    {"label": "Transportation Cost", "amount": "242.27", "door": None},
                    {"label": "Supplies & Materials", "amount": "150", "door": None},
                    {"label": "Electricity", "amount": "17.22", "door": None},
                    {"label": "Water", "amount": "144.36", "door": None},
                    {"label": "Utilities (Landlord Paid)", "amount": "161.58", "door": None},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "1232.50"},
                ],
            },
            12: {
                "income": "0",
                "operating_expenses": "1262.31",
                "noi": "-1262.31",
                "expense_lines": [
                    {"label": "Property Management Fees", "amount": "100", "door": None},
                    {"label": "Repairs & Maintenance", "amount": "200", "door": None},
                    {"label": "Property Taxes", "amount": "453.67", "door": None},
                    {"label": "Insurance", "amount": "183.83", "door": None},
                    {"label": "HOA Fees", "amount": "37.50", "door": None},
                    {"label": "Transportation Cost", "amount": "15.14", "door": None},
                    {"label": "Supplies & Materials", "amount": "150", "door": None},
                    {"label": "Electricity", "amount": "17.53", "door": None},
                    {"label": "Water", "amount": "104.64", "door": None},
                    {"label": "Utilities (Landlord Paid)", "amount": "122.17", "door": None},
                ],
                "financing_lines": [
                    {"label": "Mortgage Interest", "amount": "1232.50"},
                ],
            },
        },
    },
    {
        "group_key": "Avenue H",
        "sheet": "Ave_H",
        "year": 2025,
        "match_names": ["Avenue H", "Ave H", "7425 Avenue H", "7427 Avenue H", "7429 Avenue H", "7430 Avenue H"],
        "address": "7425, 7427, 7429 and 7430 Avenue H, Houston, Texas",
        "financials": {
            "purchase_price": "300000",
            "down_payment": "41513.32",
            "loan_amount": "275580.06",
            "interest_rate": "0.09",
            "loan_term_years": "30",
            "monthly_mortgage_payment": "2025",
            "escrow_notes": "Seller Finance Via David Hesham. 5 Year Maturity (July 10, 2030)",
        },
        "months": {
            1: {
                "income": "850",
                "operating_expenses": "1161.65",
                "noi": "-311.65",
                "unit_income": [
                    {"door": 4, "amount": "850", "status": "occupied"},
                ],
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 1", "amount": "30", "door": 1},
                    {"label": "Repairs & Maintenance - Unit 1", "amount": "175", "door": 1},
                    {"label": "Cleaning Fees - Unit 1", "amount": "60", "door": 1},
                    {"label": "Supplies & Materials - Unit 1", "amount": "50", "door": 1},
                    {"label": "Electricity - Unit 1", "amount": "148.69", "door": 1},
                    {"label": "Water - Unit 1", "amount": "137.35", "door": 1},
                    {"label": "Internet - Unit 1", "amount": "23.55", "door": 1},
                    {"label": "Property Management Fees - Unit 2", "amount": "30", "door": 2},
                    {"label": "Repairs & Maintenance - Unit 2", "amount": "175", "door": 2},
                    {"label": "Cleaning Fees - Unit 2", "amount": "60", "door": 2},
                    {"label": "Supplies & Materials - Unit 2", "amount": "50", "door": 2},
                    {"label": "Electricity - Unit 2", "amount": "125.46", "door": 2},
                    {"label": "Water - Unit 2", "amount": "43.05", "door": 2},
                    {"label": "Internet - Unit 2", "amount": "23.55", "door": 2},
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            2: {
                "income": "850",
                "operating_expenses": "1100.86",
                "noi": "-250.86",
                "unit_income": [
                    {"door": 4, "amount": "850", "status": "vacant"},
                ],
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 1", "amount": "40", "door": 1},
                    {"label": "Cleaning Fees - Unit 1", "amount": "300", "door": 1},
                    {"label": "Supplies & Materials - Unit 1", "amount": "50", "door": 1},
                    {"label": "Electricity - Unit 1", "amount": "100.11", "door": 1},
                    {"label": "Water - Unit 1", "amount": "34.65", "door": 1},
                    {"label": "Internet - Unit 1", "amount": "23.55", "door": 1},
                    {"label": "Property Management Fees - Unit 2", "amount": "40", "door": 2},
                    {"label": "Cleaning Fees - Unit 2", "amount": "240", "door": 2},
                    {"label": "Supplies & Materials - Unit 2", "amount": "50", "door": 2},
                    {"label": "Electricity - Unit 2", "amount": "133.82", "door": 2},
                    {"label": "Water - Unit 2", "amount": "35.18", "door": 2},
                    {"label": "Internet - Unit 2", "amount": "23.55", "door": 2},
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            3: {
                "income": "850",
                "operating_expenses": "1361.86",
                "noi": "-511.86",
                "unit_income": [
                    {"door": 4, "amount": "850", "status": "vacant"},
                ],
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 1", "amount": "40", "door": 1},
                    {"label": "Cleaning Fees - Unit 1", "amount": "240", "door": 1},
                    {"label": "Supplies & Materials - Unit 1", "amount": "50", "door": 1},
                    {"label": "Electricity - Unit 1", "amount": "134.42", "door": 1},
                    {"label": "Water - Unit 1", "amount": "87.52", "door": 1},
                    {"label": "Internet - Unit 1", "amount": "23.55", "door": 1},
                    {"label": "Property Management Fees - Unit 2", "amount": "40", "door": 2},
                    {"label": "Cleaning Fees - Unit 2", "amount": "240", "door": 2},
                    {"label": "Supplies & Materials - Unit 2", "amount": "50", "door": 2},
                    {"label": "Electricity - Unit 2", "amount": "158.91", "door": 2},
                    {"label": "Water - Unit 2", "amount": "70.36", "door": 2},
                    {"label": "Internet - Unit 2", "amount": "23.55", "door": 2},
                    {"label": "Property Management Fees - Unit 3", "amount": "40", "door": 3},
                    {"label": "Cleaning Fees - Unit 3", "amount": "60", "door": 3},
                    {"label": "Supplies & Materials - Unit 3", "amount": "50", "door": 3},
                    {"label": "Internet - Unit 3", "amount": "23.55", "door": 3},
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            4: {
                "income": "850",
                "operating_expenses": "1848.84",
                "noi": "-998.84",
                "unit_income": [
                    {"door": 4, "amount": "850", "status": "vacant"},
                ],
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 1", "amount": "40", "door": 1},
                    {"label": "Cleaning Fees - Unit 1", "amount": "300", "door": 1},
                    {"label": "Supplies & Materials - Unit 1", "amount": "50", "door": 1},
                    {"label": "Electricity - Unit 1", "amount": "129.42", "door": 1},
                    {"label": "Water - Unit 1", "amount": "123.44", "door": 1},
                    {"label": "Internet - Unit 1", "amount": "23.55", "door": 1},
                    {"label": "Property Management Fees - Unit 2", "amount": "40", "door": 2},
                    {"label": "Cleaning Fees - Unit 2", "amount": "240", "door": 2},
                    {"label": "Supplies & Materials - Unit 2", "amount": "50", "door": 2},
                    {"label": "Electricity - Unit 2", "amount": "124.20", "door": 2},
                    {"label": "Water - Unit 2", "amount": "105.54", "door": 2},
                    {"label": "Internet - Unit 2", "amount": "23.55", "door": 2},
                    {"label": "Property Management Fees - Unit 3", "amount": "40", "door": 3},
                    {"label": "Cleaning Fees - Unit 3", "amount": "240", "door": 3},
                    {"label": "Supplies & Materials - Unit 3", "amount": "50", "door": 3},
                    {"label": "Electricity - Unit 3", "amount": "84.53", "door": 3},
                    {"label": "Water - Unit 3", "amount": "131.06", "door": 3},
                    {"label": "Internet - Unit 3", "amount": "23.55", "door": 3},
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            5: {
                "income": "850",
                "operating_expenses": "789.97",
                "noi": "60.03",
                "unit_income": [
                    {"door": 4, "amount": "850", "status": "vacant"},
                ],
                "expense_lines": [
                    {"label": "Supplies & Materials - Unit 1", "amount": "50", "door": 1},
                    {"label": "Electricity - Unit 1", "amount": "115.94", "door": 1},
                    {"label": "Internet - Unit 1", "amount": "23.55", "door": 1},
                    {"label": "Supplies & Materials - Unit 2", "amount": "50", "door": 2},
                    {"label": "Electricity - Unit 2", "amount": "217.71", "door": 2},
                    {"label": "Internet - Unit 2", "amount": "23.55", "door": 2},
                    {"label": "Supplies & Materials - Unit 3", "amount": "50", "door": 3},
                    {"label": "Electricity - Unit 3", "amount": "169.52", "door": 3},
                    {"label": "Water - Unit 3", "amount": "36.15", "door": 3},
                    {"label": "Internet - Unit 3", "amount": "23.55", "door": 3},
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            6: {
                "income": "850",
                "operating_expenses": "640.63",
                "noi": "209.37",
                "unit_income": [
                    {"door": 4, "amount": "850", "status": "vacant"},
                ],
                "expense_lines": [
                    {"label": "Supplies & Materials - Unit 1", "amount": "50", "door": 1},
                    {"label": "Electricity - Unit 1", "amount": "237.02", "door": 1},
                    {"label": "Supplies & Materials - Unit 2", "amount": "50", "door": 2},
                    {"label": "Electricity - Unit 2", "amount": "227.52", "door": 2},
                    {"label": "Water - Unit 3", "amount": "46.09", "door": 3},
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            7: {
                "income": "850",
                "operating_expenses": "737.89",
                "noi": "112.11",
                "unit_income": [
                    {"door": 4, "amount": "850", "status": "vacant"},
                ],
                "expense_lines": [
                    {"label": "Supplies & Materials - Unit 1", "amount": "50", "door": 1},
                    {"label": "Electricity - Unit 1", "amount": "251.52", "door": 1},
                    {"label": "Supplies & Materials - Unit 2", "amount": "50", "door": 2},
                    {"label": "Electricity - Unit 2", "amount": "356.37", "door": 2},
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            8: {
                "income": "850",
                "operating_expenses": "30.00",
                "noi": "820.00",
                "unit_income": [
                    {"door": 4, "amount": "850", "status": "vacant"},
                ],
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            9: {
                "income": "850",
                "operating_expenses": "30.00",
                "noi": "820.00",
                "unit_income": [
                    {"door": 4, "amount": "850", "status": "vacant"},
                ],
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            10: {
                "income": "850",
                "operating_expenses": "30.00",
                "noi": "820.00",
                "unit_income": [
                    {"door": 4, "amount": "850", "status": "vacant"},
                ],
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            11: {
                "income": "850",
                "operating_expenses": "30.00",
                "noi": "820.00",
                "unit_income": [
                    {"door": 4, "amount": "850", "status": "vacant"},
                ],
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            12: {
                "income": "850",
                "operating_expenses": "30.00",
                "noi": "820.00",
                "unit_income": [
                    {"door": 4, "amount": "850", "status": "vacant"},
                ],
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
        },
    },
    {
        "group_key": "Avenue F",
        "sheet": "Ave_F",
        "year": 2026,
        "match_names": ["Avenue F", "Ave F", "7304 Avenue F"],
        "address": "7304 Avenue F, Houston, Texas",
        "financials": {
            "purchase_price": "180000",
            "down_payment": "18000",
            "loan_amount": "162000",
            "interest_rate": "0.08",
            "loan_term_years": "30",
            "monthly_mortgage_payment": "1189",
            "escrow_notes": "Seller Finance Via David Hesham",
        },
        "months": {
            1: {
                "income": "0",
                "operating_expenses": "30",
                "noi": "-30",
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            2: {
                "income": "0",
                "operating_expenses": "30",
                "noi": "-30",
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            3: {
                "income": "0",
                "operating_expenses": "30",
                "noi": "-30",
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            4: {
                "income": "0",
                "operating_expenses": "30",
                "noi": "-30",
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            5: {
                "income": "0",
                "operating_expenses": "30",
                "noi": "-30",
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            6: {
                "income": "0",
                "operating_expenses": "30",
                "noi": "-30",
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            7: {
                "income": "0",
                "operating_expenses": "30",
                "noi": "-30",
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            8: {
                "income": "0",
                "operating_expenses": "30",
                "noi": "-30",
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            9: {
                "income": "0",
                "operating_expenses": "30",
                "noi": "-30",
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            10: {
                "income": "0",
                "operating_expenses": "30",
                "noi": "-30",
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            11: {
                "income": "0",
                "operating_expenses": "30",
                "noi": "-30",
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            12: {
                "income": "0",
                "operating_expenses": "30",
                "noi": "-30",
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
        },
    },
    {
        "group_key": "Wooding St",
        "sheet": "Wooding",
        "year": 2026,
        "match_names": ["Wooding", "903 Wooden Street", "903 Wooden"],
        "address": "903 Wooden Street, Houston, Texas",
        "financials": {
            "purchase_price": "216507",
            "down_payment": "16507",
            "loan_amount": "200000",
            "interest_rate": "0.09",
            "loan_term_years": "30",
            "monthly_mortgage_payment": "1610",
            "escrow_notes": "Seller Finance Via David Hesham",
        },
        "months": {
            1: {
                "income": "0",
                "operating_expenses": "100.11",
                "noi": "-100.11",
                "expense_lines": [
                    {"label": "Electricity - Unit 2", "amount": "14.90", "door": 2},
                    {"label": "Water - Unit 2", "amount": "85.21", "door": 2},
                ],
            },
            2: {
                "income": "0",
                "operating_expenses": "65.36",
                "noi": "-65.36",
                "expense_lines": [
                    {"label": "Electricity - Unit 2", "amount": "21.50", "door": 2},
                    {"label": "Water - Unit 2", "amount": "43.86", "door": 2},
                ],
            },
            3: {
                "income": "0",
                "operating_expenses": "821.97",
                "noi": "-821.97",
                "expense_lines": [
                    {"label": "Repairs & Maintenance - Unit 1", "amount": "750", "door": 1},
                    {"label": "Electricity - Unit 2", "amount": "28.11", "door": 2},
                    {"label": "Water - Unit 2", "amount": "43.86", "door": 2},
                ],
            },
            4: {
                "income": "0",
                "operating_expenses": "502.77",
                "noi": "-502.77",
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 2", "amount": "40", "door": 2},
                    {"label": "Cleaning Fees - Unit 2", "amount": "160", "door": 2},
                    {"label": "Supplies & Materials - Unit 2", "amount": "50", "door": 2},
                    {"label": "Electricity - Unit 2", "amount": "84.53", "door": 2},
                    {"label": "Water - Unit 2", "amount": "55.24", "door": 2},
                    {"label": "Internet - Unit 2", "amount": "41.52", "door": 2},
                    {"label": "Water - Unit 3", "amount": "71.48", "door": 3},
                ],
            },
            5: {
                "income": "0",
                "operating_expenses": "529.88",
                "noi": "-529.88",
                "expense_lines": [
                    {"label": "Supplies & Materials - Unit 2", "amount": "50", "door": 2},
                    {"label": "Electricity - Unit 2", "amount": "179.48", "door": 2},
                    {"label": "Water - Unit 2", "amount": "150.08", "door": 2},
                    {"label": "Internet - Unit 2", "amount": "150.32", "door": 2},
                ],
            },
            6: {
                "income": "0",
                "operating_expenses": "361.43",
                "noi": "-361.43",
                "expense_lines": [
                    {"label": "Supplies & Materials - Unit 2", "amount": "50", "door": 2},
                    {"label": "Electricity - Unit 2", "amount": "211.35", "door": 2},
                    {"label": "Water - Unit 2", "amount": "100.08", "door": 2},
                ],
            },
            7: {
                "income": "0",
                "operating_expenses": "372.60",
                "noi": "-372.60",
                "expense_lines": [
                    {"label": "Supplies & Materials - Unit 2", "amount": "50", "door": 2},
                    {"label": "Electricity - Unit 2", "amount": "222.52", "door": 2},
                    {"label": "Water - Unit 2", "amount": "100.08", "door": 2},
                ],
            },
            8: {"income": "0", "operating_expenses": "0", "noi": "0"},
            9: {"income": "0", "operating_expenses": "0", "noi": "0"},
            10: {"income": "0", "operating_expenses": "0", "noi": "0"},
            11: {"income": "0", "operating_expenses": "0", "noi": "0"},
            12: {"income": "0", "operating_expenses": "0", "noi": "0"},
        },
    },
    {
        "group_key": "70th Street",
        "sheet": "70th",
        "year": 2026,
        "match_names": ["70th", "1403 70th Street", "1403 70th"],
        "address": "1403 70th Street, Houston, Texas",
        "financials": {
            "purchase_price": "274000",
            "down_payment": "30000",
            "loan_amount": "274000",
            "interest_rate": "0.09",
            "loan_term_years": "30",
            "monthly_mortgage_payment": "2192",
            "escrow_notes": "Seller Finance Via David Hesham",
        },
        "months": {
            1: {
                "income": "0",
                "operating_expenses": "30",
                "noi": "-30",
                "unit_income": [],
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            2: {
                "income": "850",
                "operating_expenses": "30",
                "noi": "820",
                "unit_income": [
                    {"door": 4, "amount": "850", "status": "vacant"},
                ],
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            3: {
                "income": "850",
                "operating_expenses": "30",
                "noi": "820",
                "unit_income": [
                    {"door": 4, "amount": "850", "status": "vacant"},
                ],
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            4: {
                "income": "850",
                "operating_expenses": "30",
                "noi": "820",
                "unit_income": [
                    {"door": 4, "amount": "850", "status": "vacant"},
                ],
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            5: {
                "income": "850",
                "operating_expenses": "30",
                "noi": "820",
                "unit_income": [
                    {"door": 4, "amount": "850", "status": "vacant"},
                ],
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            6: {
                "income": "850",
                "operating_expenses": "30",
                "noi": "820",
                "unit_income": [
                    {"door": 4, "amount": "850", "status": "vacant"},
                ],
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            7: {
                "income": "850",
                "operating_expenses": "30",
                "noi": "820",
                "unit_income": [
                    {"door": 4, "amount": "850", "status": "vacant"},
                ],
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            8: {
                "income": "850",
                "operating_expenses": "30",
                "noi": "820",
                "unit_income": [
                    {"door": 4, "amount": "850", "status": "vacant"},
                ],
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            9: {
                "income": "0",
                "operating_expenses": "30",
                "noi": "-30",
                "unit_income": [],
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            10: {
                "income": "850",
                "operating_expenses": "30",
                "noi": "820",
                "unit_income": [
                    {"door": 4, "amount": "850", "status": "vacant"},
                ],
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            11: {
                "income": "850",
                "operating_expenses": "30",
                "noi": "820",
                "unit_income": [
                    {"door": 4, "amount": "850", "status": "vacant"},
                ],
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
            12: {
                "income": "850",
                "operating_expenses": "30",
                "noi": "820",
                "unit_income": [
                    {"door": 4, "amount": "850", "status": "vacant"},
                ],
                "expense_lines": [
                    {"label": "Property Management Fees - Unit 4", "amount": "30", "door": 4},
                ],
            },
        },
    },
]
